### ISSUE TITLE
Doesn't need to change docker-compose file

### ISSUE THREAD

**Issue by blackerking** [Kailona/kailona-fhir-server#3]
Hello,

I recently used Apache Guacamole and it depends on a PostgreSQL database.
Other than your software it doesn't need to change any value(inside your docker-compose file) for a already set database.

Maybe you can add this.

related Link:
[https://hub.docker.com/r/guacamole/guacamole](https://hub.docker.com/r/guacamole/guacamole)

best regards

**Comment by makuser** [comment]
Well, go ahead and run the server just like guacamole: https://hub.docker.com/r/ibmcom/ibm-fhir-server.

This repo makes it much easier to just get started though, by providing not only a basic configuration for the ibm-fhir-server, but also by spinning up a postgresql database and initializing the schema.

**Comment by ayselafsar** [comment]
Great to see it running with different environments, but looks like it is out of scope of this repo that just simplifies running FHIR server in docker, with minimum dependencies.
